name = "nimbus-web"
main = ".open-next/worker.js"
compatibility_date = "2025-05-18"
compatibility_flags = ["nodejs_compat", "global_fetch_strictly_public"]
observability = { enabled = true }

[assets]
binding = "ASSETS"
directory = ".open-next/assets"

[dev]
port = 3000
local_protocol = "http"
host = "localhost"

[env.preview]

[env.staging]
routes = [{ pattern = "staging.nimbus.storage", custom_domain = true }]

[env.production]
routes = [{ pattern = "nimbus.storage", custom_domain = true }]
